
import { TarotCard } from '../types';
import * as Images from '../assets/index';


export const TAROT_DECK: TarotCard[] = [
  // Major Arcana
  { name: 'The Fool', cardImg: Images.TheFool },
  { name: 'The Magician', cardImg: Images.TheMagician },
  { name: 'The High Priestess', cardImg: Images.TheHighPriestess },
  { name: 'The Empress', cardImg: Images.TheEmpress },
  { name: 'The Emperor', cardImg: Images.TheEmperor },
  { name: 'The Hierophant', cardImg: Images.TheHierophant },
  { name: 'The Lovers', cardImg: Images.TheLovers },
  { name: 'The Chariot', cardImg: Images.TheChariot },
  { name: 'Strength', cardImg: Images.Strength },
  { name: 'The Hermit', cardImg: Images.TheHermit },
  { name: 'Wheel of Fortune', cardImg: Images.WheelOfFortune },
  { name: 'Justice', cardImg: Images.Justice },
  { name: 'The Hanged Man', cardImg: Images.TheHangedMan },
  { name: 'Death', cardImg: Images.Death },
  { name: 'Temperance', cardImg: Images.Temperance },
  { name: 'The Devil', cardImg: Images.TheDevil },
  { name: 'The Tower', cardImg: Images.TheTower },
  { name: 'The Star', cardImg: Images.TheStar },
  { name: 'The Moon', cardImg: Images.TheMoon },
  { name: 'The Sun', cardImg: Images.TheSun },
  { name: 'Judgement', cardImg: Images.Judgement },
  { name: 'The World', cardImg: Images.TheWorld },
  
  // Cups
  { name: 'Ace of Cups', cardImg: Images.AceOfCups },
  { name: 'Two of Cups', cardImg: Images.TwoOfCups },
  { name: 'Three of Cups', cardImg: Images.ThreeOfCups },
  { name: 'Four of Cups', cardImg: Images.FourOfCups },
  { name: 'Five of Cups', cardImg: Images.FiveOfCups },
  { name: 'Six of Cups', cardImg: Images.SixOfCups },
  { name: 'Seven of Cups', cardImg: Images.SevenOfCups },
  { name: 'Eight of Cups', cardImg: Images.EightOfCups },
  { name: 'Nine of Cups', cardImg: Images.NineOfCups },
  { name: 'Ten of Cups', cardImg: Images.TenOfCups },
  { name: 'Page of Cups', cardImg: Images.PageOfCups },
  { name: 'Knight of Cups', cardImg: Images.KnightOfCups },
  { name: 'Queen of Cups', cardImg: Images.QueenOfCups },
  { name: 'King of Cups', cardImg: Images.KingOfCups },
  
  // Wands
  { name: 'Ace of Wands', cardImg: Images.AceOfWands },
  { name: 'Two of Wands', cardImg: Images.TwoOfWands },
  { name: 'Three of Wands', cardImg: Images.ThreeOfWands },
  { name: 'Four of Wands', cardImg: Images.FourOfWands },
  { name: 'Five of Wands', cardImg: Images.FiveOfWands },
  { name: 'Six of Wands', cardImg: Images.SixOfWands },
  { name: 'Seven of Wands', cardImg: Images.SevenOfWands },
  { name: 'Eight of Wands', cardImg: Images.EightOfWands },
  { name: 'Nine of Wands', cardImg: Images.NineOfWands },
  { name: 'Ten of Wands', cardImg: Images.TenOfWands },
  { name: 'Page of Wands', cardImg: Images.PageOfWands },
  { name: 'Knight of Wands', cardImg: Images.KnightOfWands },
  { name: 'Queen of Wands', cardImg: Images.QueenOfWands },
  { name: 'King of Wands', cardImg: Images.KingOfWands },
  
  // Swords
  { name: 'Ace of Swords', cardImg: Images.AceOfSwords },
  { name: 'Two of Swords', cardImg: Images.TwoOfSwords },
  { name: 'Three of Swords', cardImg: Images.ThreeOfSwords },
  { name: 'Four of Swords', cardImg: Images.FourOfSwords },
  { name: 'Five of Swords', cardImg: Images.FiveOfSwords },
  { name: 'Six of Swords', cardImg: Images.SixOfSwords },
  { name: 'Seven of Swords', cardImg: Images.SevenOfSwords },
  { name: 'Eight of Swords', cardImg: Images.EightOfSwords },
  { name: 'Nine of Swords', cardImg: Images.NineOfSwords },
  { name: 'Ten of Swords', cardImg: Images.TenOfSwords },
  { name: 'Page of Swords', cardImg: Images.PageOfSwords },
  { name: 'Knight of Swords', cardImg: Images.KnightOfSwords },
  { name: 'Queen of Swords', cardImg: Images.QueenOfSwords },
  { name: 'King of Swords', cardImg: Images.KingOfSwords },
  
  // Pentacles
  { name: 'Ace of Pentacles', cardImg: Images.AceOfPentacles },
  { name: 'Two of Pentacles', cardImg: Images.TwoOfPentacles },
  { name: 'Three of Pentacles', cardImg: Images.ThreeOfPentacles },
  { name: 'Four of Pentacles', cardImg: Images.FourOfPentacles },
  { name: 'Five of Pentacles', cardImg: Images.FiveOfPentacles },
  { name: 'Six of Pentacles', cardImg: Images.SixOfPentacles },
  { name: 'Seven of Pentacles', cardImg: Images.SevenOfPentacles },
  { name: 'Eight of Pentacles', cardImg: Images.EightOfPentacles },
  { name: 'Nine of Pentacles', cardImg: Images.NineOfPentacles },
  { name: 'Ten of Pentacles', cardImg: Images.TenOfPentacles },
  { name: 'Page of Pentacles', cardImg: Images.PageOfPentacles },
  { name: 'Knight of Pentacles', cardImg: Images.KnightOfPentacles },
  { name: 'Queen of Pentacles', cardImg: Images.QueenOfPentacles },
  { name: 'King of Pentacles', cardImg: Images.KingOfPentacles },
]